### ISSUE TITLE
Migrating notebooks

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm-examples#4]
The mitgcm and MOM6 examples are both producing errors. Could the authors check on those?

**Comment by jbusecke** [comment]
I fixed the mitgcm version. @raphaeldussin, I just checked the MOM6 example and it seems that the grid file
```!curl -O https://raw.githubusercontent.com/raphaeldussin/MOM6-AnalysisCookbook/master/tutorials/data/ocean_grid_sym_OM4_05.nc``` 
is not present in the latest version of [MOM6-AnalysisCookbook](https://github.com/raphaeldussin/MOM6-AnalysisCookbook)? 

I could add it to the [example zenodo archive](https://zenodo.org/record/4421428#.X_XcsC1h3x-) if you have permission to share that file.

**Comment by raphaeldussin** [comment]
@jbusecke ok this is due to my refactoring, I'll fix this and I also have a couple of edits I want to make

**Comment by jbusecke** [comment]
Great! Thank you!

**Comment by raphaeldussin** [comment]
MOM6 notebook fixed in #6
